In [124]:
from pyforest import *

from sklearn.model_selection import train_test_split

from sklearn.metrics import classification_report

from sklearn.svm import SVC

from catboost import CatBoostClassifier

from sklearn.preprocessing import StandardScaler

import warnings
warnings.filterwarnings("ignore")

from sklearn.linear_model import LogisticRegression

In [2]:
df= pd.read_csv(r"train_ctrUa4K.csv")

df.head()

<IPython.core.display.Javascript object>

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

In [3]:
df.Gender.value_counts()

Male      489
Female    112
Name: Gender, dtype: int64

In [4]:
df.shape

(614, 13)

In [5]:
df.dtypes

Loan_ID               object
Gender                object
Married               object
Dependents            object
Education             object
Self_Employed         object
ApplicantIncome        int64
CoapplicantIncome    float64
LoanAmount           float64
Loan_Amount_Term     float64
Credit_History       float64
Property_Area         object
Loan_Status           object
dtype: object

In [6]:
df.isnull().sum()



Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [7]:
df= df.fillna(method="ffill")

In [8]:
df= df.fillna(method="bfill")

In [9]:
df.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0       128.0             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

In [10]:
df.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [11]:
df.dtypes

Loan_ID               object
Gender                object
Married               object
Dependents            object
Education             object
Self_Employed         object
ApplicantIncome        int64
CoapplicantIncome    float64
LoanAmount           float64
Loan_Amount_Term     float64
Credit_History       float64
Property_Area         object
Loan_Status           object
dtype: object

In [12]:
df= df.drop("Loan_ID", axis=1)

In [13]:
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_selection import SelectKBest

In [14]:
lr= LabelEncoder()

In [15]:
df["Gender"]= lr.fit_transform(df.Gender.values)
df["Married"]= lr.fit_transform(df.Married.values)
df["Dependents"]= lr.fit_transform(df.Dependents.values)
df["Education"]= lr.fit_transform(df.Education.values)
df["Self_Employed"]= lr.fit_transform(df.Self_Employed.values)
df["Property_Area"]= lr.fit_transform(df.Property_Area.values)

In [16]:
df.head()

Gender  Married  Dependents  Education  Self_Employed  ApplicantIncome  \
0       1        0           0          0              0             5849   
1       1        1           1          0              0             4583   
2       1        1           0          0              1             3000   
3       1        1           0          1              0             2583   
4       1        0           0          0              0             6000   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                0.0       128.0             360.0             1.0   
1             1508.0       128.0             360.0             1.0   
2                0.0        66.0             360.0             1.0   
3             2358.0       120.0             360.0             1.0   
4                0.0       141.0             360.0             1.0   

   Property_Area Loan_Status  
0              2           Y  
1              0           N  
2              2           Y  
3              2           Y  
4              2           Y

In [17]:
df.Gender.value_counts()

1    500
0    114
Name: Gender, dtype: int64

In [18]:
y= (df.Loan_Status)
y.shape

(614,)

In [19]:
np.unique(y)

<IPython.core.display.Javascript object>

array(['N', 'Y'], dtype=object)

In [20]:
y_new= lr.fit_transform(y.values)

In [21]:
y_new

array([1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0,

In [22]:
SelectKBest?

### Feature Selection using Filter Based Methods

In [37]:
from sklearn.feature_selection import chi2, f_classif


In [100]:
F= SelectKBest(score_func=f_classif,k=3)

In [101]:
F

SelectKBest(k=3)

In [102]:
X= np.asarray(df.drop("Loan_Status", axis=1))

<IPython.core.display.Javascript object>

In [103]:
X

array([[  1.,   0.,   0., ..., 360.,   1.,   2.],
       [  1.,   1.,   1., ..., 360.,   1.,   0.],
       [  1.,   1.,   0., ..., 360.,   1.,   2.],
       ...,
       [  1.,   1.,   1., ..., 360.,   1.,   2.],
       [  1.,   1.,   2., ..., 360.,   1.,   2.],
       [  0.,   0.,   0., ..., 360.,   0.,   1.]])

In [104]:
T=F.fit(X,y_new)

In [105]:
(T.scores_)

array([9.13027499e-02, 4.89437253e+00, 6.91387582e-03, 4.54768458e+00,
       4.99576425e-02, 1.35742185e-02, 2.15145736e+00, 1.22099048e+00,
       6.82589094e-01, 2.33051983e+02, 6.31733319e-01])

In [106]:
len(T.scores_)

11

### sorting the array in descending order

In [107]:
np.sort(T.scores_)[::-1]

<IPython.core.display.Javascript object>

array([2.33051983e+02, 4.89437253e+00, 4.54768458e+00, 2.15145736e+00,
       1.22099048e+00, 6.82589094e-01, 6.31733319e-01, 9.13027499e-02,
       4.99576425e-02, 1.35742185e-02, 6.91387582e-03])

### viewing the indices of the top features

In [110]:
index= np.argsort(T.scores_)[::-1]

<IPython.core.display.Javascript object>

In [111]:
index

array([ 9,  1,  3,  6,  7,  8, 10,  0,  4,  5,  2], dtype=int64)

In [112]:
np.asarray(df.columns)[index]

<IPython.core.display.Javascript object>

array(['Credit_History', 'Married', 'Education', 'CoapplicantIncome',
       'LoanAmount', 'Loan_Amount_Term', 'Property_Area', 'Gender',
       'Self_Employed', 'ApplicantIncome', 'Dependents'], dtype=object)

In [114]:
x_new= T.transform(X)

### newly transformed shape of X as per feature selection using Anova

In [115]:
x_new.shape

(614, 3)

In [116]:
X_train, X_test, y_train, y_test= train_test_split(x_new, y_new, test_size=0.3, random_state=123)

In [117]:
X_train.shape

(429, 3)

In [132]:
model= CatBoostClassifier(iterations=40,eval_metric="Accuracy")

In [133]:
model.fit(X_train, y_train,eval_set=(X_test,y_test))

Learning rate set to 0.104287
0:	learn: 0.8181818	test: 0.7783784	best: 0.7783784 (0)	total: 984us	remaining: 38.4ms
1:	learn: 0.8181818	test: 0.7783784	best: 0.7783784 (0)	total: 2.17ms	remaining: 41.1ms
2:	learn: 0.8181818	test: 0.7783784	best: 0.7783784 (0)	total: 3ms	remaining: 37ms
3:	learn: 0.8181818	test: 0.7783784	best: 0.7783784 (0)	total: 3.87ms	remaining: 34.8ms
4:	learn: 0.8181818	test: 0.7783784	best: 0.7783784 (0)	total: 4.58ms	remaining: 32ms
5:	learn: 0.8181818	test: 0.7783784	best: 0.7783784 (0)	total: 5.35ms	remaining: 30.3ms
6:	learn: 0.8181818	test: 0.7783784	best: 0.7783784 (0)	total: 6.21ms	remaining: 29.3ms
7:	learn: 0.8181818	test: 0.7783784	best: 0.7783784 (0)	total: 7.16ms	remaining: 28.6ms
8:	learn: 0.8181818	test: 0.7783784	best: 0.7783784 (0)	total: 8.34ms	remaining: 28.7ms
9:	learn: 0.8181818	test: 0.7783784	best: 0.7783784 (0)	total: 9.32ms	remaining: 28ms
10:	learn: 0.8181818	test: 0.7783784	best: 0.7783784 (0)	total: 10.3ms	remaining: 27.2ms
11:	learn: 

In [134]:
y_pred= model.predict(X_test)

In [135]:
y_pred

array([1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [136]:
model.score(X_test,y_test)

0.7783783783783784

In [127]:
mod= LogisticRegression(penalty='l2')

In [128]:
mod.fit(X_train, y_train)

LogisticRegression()

In [129]:
y_p= mod.predict(X_test)

In [130]:
y_p

array([1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1])

In [131]:
mod.score(X_test,y_test)

0.7783783783783784

### here above we can see that the accuracy has become stagnant so let's try wrapper method and then do the rest of the things

In [137]:
from sklearn.feature_selection import RFE

In [168]:
S= RFE(mod,5)

In [169]:
r= S.fit(X,y_new)

In [170]:
r

RFE(estimator=LogisticRegression(), n_features_to_select=5)

In [171]:
mask= r.get_support()

In [172]:
mask

array([ True,  True, False,  True,  True, False, False, False, False,
        True, False])

In [173]:
x_new_1= r.transform(X)

In [174]:
x_new_1.shape

(614, 5)

In [ ]:
# we can use the below mentioned features

In [175]:
np.arange(11)[mask]

<IPython.core.display.Javascript object>

array([0, 1, 3, 4, 9])

In [176]:
X_train_1,X_test_1, y_train_1, y_test_1= train_test_split(x_new_1, y_new, test_size=0.3, random_state=42)

In [178]:
mod.fit(X_train_1, y_train_1)

LogisticRegression()

In [179]:
pred= mod.predict(X_test_1)

In [180]:
pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0])

In [181]:
mod.score(X_test_1,y_test_1)

0.7945945945945946

In [182]:
test= pd.read_csv(r"test_lAUu6dG.csv")
test.head()

<IPython.core.display.Javascript object>

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001015   Male     Yes          0      Graduate            No   
1  LP001022   Male     Yes          1      Graduate            No   
2  LP001031   Male     Yes          2      Graduate            No   
3  LP001035   Male     Yes          2      Graduate            No   
4  LP001051   Male      No          0  Not Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5720                  0       110.0             360.0   
1             3076               1500       126.0             360.0   
2             5000               1800       208.0             360.0   
3             2340               2546       100.0             360.0   
4             3276                  0        78.0             360.0   

   Credit_History Property_Area  
0             1.0         Urban  
1             1.0         Urban  
2             1.0         Urban  
3             NaN         Urban  
4             1.0         Urban

In [183]:
test= test.fillna(method="ffill")

In [184]:
test= test.fillna(method="bfill")

In [185]:
test= test.drop("Loan_ID", axis=1)

In [192]:
test["Gender"]= lr.fit_transform(test.Gender.values)
test["Married"]= lr.fit_transform(test.Married.values)
test["Dependents"]= lr.fit_transform(test.Dependents.values)
test["Education"]= lr.fit_transform(test.Education.values)
test["Self_Employed"]= lr.fit_transform(test.Self_Employed.values)
test["Property_Area"]= lr.fit_transform(test.Property_Area.values)

In [193]:
test= np.asarray(test)

<IPython.core.display.Javascript object>

In [194]:
test_new= r.transform(test)

In [196]:
test_new.shape

(367, 5)

In [197]:
test_pred= mod.predict(test_new)

In [199]:
test_pred.shape

(367,)

In [200]:
data= pd.DataFrame(test_pred, index= None)

<IPython.core.display.Javascript object>

In [201]:
data.head()

0
0  1
1  1
2  1
3  1
4  1

In [202]:
data.to_csv("submission.csv")